buildscript {
    // Define versions as variables for maintainability
    ext.kotlin_version = '1.8.10' // Compatible with AGP 7.4.2; consider updating if using AGP 8.x
    ext.pesdk_version = '10.9.0'
    ext.ksp_version = '1.8.10-1.0.9'

    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        maven { url 'https://artifactory.img.ly/artifactory/imgly' } // PESDK repository
    }

    dependencies {
        // Android Gradle Plugin
        classpath 'com.android.tools.build:gradle:8.1.1'

        // Kotlin Gradle Plugin
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

        // KSP Plugin
        classpath "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin:$ksp_version"

        // PESDK Plugin
        classpath "ly.img.android.pesdk:plugin:$pesdk_version"

        // Google Services Plugin
        classpath 'com.google.gms:google-services:4.4.2'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://artifactory.img.ly/artifactory/imgly' } // PESDK repository
        maven { url 'https://jitpack.io' } // JitPack for additional dependencies
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
